[package]
name = "dcs-grpc-stubs"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
prost = "0.13"
prost-types = "0.13"
serde.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build = "0.13"
protoc-bundled = { git = "https://github.com/sevenfifty777/protoc-bundled.git", rev = "d8e8f513cfe007a6243a7eef571677fd366d2cb9" }

[dev-dependencies]
serde_json.workspace = true

[features]
default = []
server = []
client = []
